# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falkor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='container',
            unique_together=set([('project', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'user')]),
        ),
    ]
