# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 03:56
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('falkor', '0003_auto_20161102_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'name')),
                ('image', models.CharField(max_length=200)),
                ('settings', models.TextField(blank=True, null=True)),
                ('urlPrefix', models.CharField(blank=True, max_length=200)),
                ('urlSuffix', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
