# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('falkor', '0007_auto_20161105_0454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('can_open_ide', 'Can open IDE'), ('can_start_stop', 'Can control the container'))},
        ),
    ]
