# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('falkor', '0008_auto_20161105_0632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('can_open_ide', 'Can open IDE'), ('can_start_stop', 'Can control the container'), ('can_edit_shares', 'Can edit shares'))},
        ),
    ]
