version: '2'

services:
    db:
        restart: always
        image: postgres
        volumes:
            - /var/lib/postgresql/data/
        networks:
            backend:
                aliases:
                    - db
                    
    redis:
        restart: always
        image: redis
        networks:
            channels:
                aliases:
                    - redis
                    
    web:
        depends_on:
            - redis
        restart: always
        build: ./hub
        environment:
            - "DEBUG=true"
            - "REDIS=true"
        command: daphne -b 0.0.0.0 -p 8000 falkor_project.asgi:channel_layer
        networks:
            channels:
            frontend:
                aliases:
                    - web
                    
    web-worker:
        depends_on:
            - db
            - redis
        restart: always
        build: ./hub
        environment:
            - "DEBUG=true"
            - "POSTGRES=true"
            - "REDIS=true"
        command: python manage.py runworker
        networks:
            channels:
            backend:
            
    dockerworker:
        depends_on:
            - redis
        restart: always
        build: ./hub
        environment:
            - "POSTGRES=true"
            - "REDIS=true"
        command: python manage.py dockerworker
        networks:
            channels:
            backend: 
            
    web-static:
      build: ./hub
      volumes:
        - /static
      command: python manage.py collectstatic --noinput
      
    proxy:
        restart: always
        build: ./proxy
        environment:
            - DOMAIN_NAME
        networks:
            - frontend
        ports:
            - "80:8080"
        volumes_from:
            - web-static:ro

networks:
    backend:
    channels:
    frontend:
