version: '2'

services:
    db:
        restart: always
        image: postgres
        volumes:
            - /var/lib/postgresql/data/
        networks:
            backend:
                aliases:
                    - db
    web:
        depends_on:
            - db
        restart: always
        build: ./hub
        environment:
            - "DEBUG=true"
            - "POSTGRES=true"
        command: /usr/local/bin/gunicorn falkor_project.wsgi:application -w 2 -b :8000 --error-logfile - --access-logfile -
        networks:
            backend:
                aliases:
                    - web
                    
    web-static:
      build: ./hub
      volumes:
        - /static
      command: python manage.py collectstatic --noinput
      
    proxy:
        restart: always
        build: ./proxy
        environment:
            - DOMAIN_NAME
        networks:
            - backend
        ports:
            - "80:8080"
        volumes_from:
            - web-static:ro

networks:
    backend:
