SOCIAL_AUTH_GITHUB_KEY = ''
SOCIAL_AUTH_GITHUB_SECRET = ''

SOCIAL_AUTH_LOGIN_URL          = '/login'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_LOGIN_ERROR_URL    = '/login-error/'


SESSION_COOKIE_DOMAIN = '.localhost.be'

USE_X_FORWARDED_HOST = True
SOCIAL_AUTH_SANITIZE_REDIRECTS = False

DOCKER_API = '1.23'